blueprints/auth.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask import Blueprint, render_template, jsonify
from models import EmailCaptchaModel, UserModel
from flask import request, redirect, url_for,session
from .forms import RegisterForm, LoginForm
from flask_mail import Message
from datetime import datetime
from exts import mail, db
import string
import random


bp = Blueprint("auth",__name__, url_prefix="/auth")


@bp.route('/login', methods = ['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template("login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = UserModel.query.filter_by(email=email).first()
            if not user:
                print('邮箱在数据库中不存在')
                return redirect(url_for("auth.login"))
            if check_password_hash(user.password, password):
                session['user_id'] = user.id
                return redirect(url_for("qa.public_question"))
            else :
                print('密码错误')
                return redirect(url_for("auth.login"))
            return (redirect(url_for('auth.register')))

        else:
            print(form.errors)
            return redirect(url_for("auth.login"))



@bp.route('/register',methods =["GET", "POST"])
def register():
    if request.method == 'GET':
        return render_template("register.html")
    else:
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            user = UserModel(email= email, username=username, password= generate_password_hash(password))
            db.session.add(user)
            db.session.commit()
            # return redirect('/auth/login')

            return redirect(url_for('auth.login'))
        else:
            print(form.errors)
            return "fail"

# 验证码发送测试
@bp.route('/mail/test')
def mail_test():
    
    message = Message(subject="邮箱测试", recipients=["2735919386@qq.com"], body=f"我的宝贝，现在是:{datetime.now()}")
    mail.send(message)
    return "邮件再次发送成功"

@bp.route('/captcha/email')
def get_email_captcha():

    email = request.args.get("eee")            # 这里抽了email不可以
    print(email)
    source = string.digits *4 
    captcha = random.sample(source, 4)
    print(captcha)
    captcha = ''.join(captcha)
    print(captcha)
    message = Message(subject="rk_website注册登录", recipients=[email], body=f"这是rk_website发送的注册验证码{captcha},快lai收啦！发送时间：{datetime.now()}")  # 耗时操作扔给其他进程  写个装饰器起个线程去做
    mail.send(message)

    email_captcha = EmailCaptchaModel(email=email, captcha= captcha)
    db.session.add(email_captcha)
    db.session.commit()


    return jsonify({"code":200, "message": "1332", })


# http://127.0.0.1:5000/auth/captcha/email?eamil=2735919386@qq.com
# http://127.0.0.1:5000/auth/captcha/email?eee=2735919386@qq.com
# /mail/test

@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('qa.index'))

blueprints/qa.py
from flask import Blueprint, render_template,request, g,redirect, url_for
from .forms import QusetionForm, AnswerForm
from models import QuestionModel, AnswerModel
from exts import db
from decorators import login_required

bp = Blueprint("qa", __name__, url_prefix="/qa")

# 127.0.0.1:5000
@bp.route("/public_question", methods= ["GET", "POST"]) # 发布问题页
@login_required
def public_question():
    if request.method == "GET":             #   浏览器会尝试解析url发送get请求，url从a标签中来
        return render_template('public_question.html')
    else:
        form = QusetionForm(request.form)      # 这里进行数据校验, 提交的内容由html定义
        if form.validate():
            title = form.title.data
            content = form.content.data
            question = QuestionModel(title= title, content= content ,author = g.user)   # g.user在每次请求前都会拿到；author是一个外键的实例对象：负责接收的
            db.session.add(question)
            db.session.commit()
            return redirect(url_for('qa.index'))
        else:
            print(form.errors)
            return redirect(url_for("qa.public_question"))
        
@bp.route('/index')         # 这个是一个首页的显示方式：根据时间进行逆序排序返回；最新的会放在上面
def index():
    questions = QuestionModel.query.order_by(QuestionModel.create_time.desc()).all()   # 分页查询待补充
    return render_template('index.html', questions=questions)

@bp.route('/detail/<qa_id>')        # 跳转到详情页，会传进来一个参数是问题的id
def detail(qa_id):
    question = QuestionModel.query.get(qa_id)

    return render_template('detail.html', question= question)


# @bp.post("/answer/public") # 路由的另外一种写法
@bp.route('/answer/public', methods = ['POST'])
@login_required              # 只有登录了才能够评论
def public_answer():

    form = AnswerForm(request.form, methods=["POST"])
    print(form)
    print(form.question_id.data)
    if form.validate():
        print('hhhhhhhhhh')
        content = form.content.data
        print(content)
        question_id = form.question_id.data
        print(question_id)
        answer = AnswerModel(content = content, question_id=question_id, author_id = g.user.id)   #传入的参数要和和接口给的参数一致; author_id 又写错了...
        db.session.add(answer)
        db.session.commit()
        return redirect(url_for('qa.detail', qa_id = question_id))      # url_for 要写到一起，参数和地址


    else:
        print(form.errors)
        return redirect(url_for('qa.detail', qa_id = request.form.get("question_id")))
    
@bp.route('/search')
def search():
    q = request.args.get("q")
    questions = QuestionModel.query.filter(QuestionModel.title.contains(q)).all()
    return render_template("index.html",questions=questions)

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <!-- 加一行测试注释 -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/bootstrap.4.6.min.css') }}">
<!--    <link rel="stylesheet" href="{{url_for('static',filename='bootstrap/bootstrap.4.6.min.css') }}">-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/init.css') }}">

    <title>{% block title %}{% endblock %}</title>
<!--    详情页面自己的css,js都放在header当中-->
    {% block head %}{% endblock %}
<!--    标题自定义-->
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <img class="nav-item" src="{{url_for('static', filename = 'images/logo.png')}}" alt="加载错误！" width="30px" height="30px">&nbsp
            <a class="navbar-brand" href="{{url_for("qa.index")}}">众承数据集问答平台</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{{url_for("qa.index")}}">首页 <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for("qa.public_question")}}">发布问答</a>
                    </li>
                    <li class="nav-item ml-2">
                        <form class="form-inline my-2 my-lg-0" method="GET" action="{{url_for("qa.search")}}">
                            <input class="form-control mr-sm-2" type="search" placeholder="关键字" aria-label="Search" name="q">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
                        </form>
                    </li>
                </ul>

                <ul class="navbar-nav">
                    {% if user %}
                        <li class="nav-item">
                            <span class="nav-link" href="#">{{user.username}}</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('auth.logout')}}">退出登录</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('auth.login')}}">登录</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('auth.register')}}">注册</a>
                        </li>
                    {% endif %}
                </ul>

            </div>
        </div>
    </nav>

    <div class="container">
        {% block body%}{% endblock %}
    </div>
</body>

</html>

templates/detail.html
{% extends "base.html" %}

{% block title%}{{question.title}}{%endblock%}

{% block head%}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/detail.css')}}">
{% endblock%}

{%block body%}
<div class="row" style="margin-top: 20px;">
    <div class="col"></div>
    <div class="col-10" style="background-color: #fff;padding: 20px;">
        <h3 class="page-title">{{question.title}}</h3>
        <p class="question-info">
            <span>作者：{{question.author.username}}</span>
            <span>时间：{{question.create_time}}</span>
        </p>
        <hr>
        <p class="question-content">{{question.content}}</p>
        <hr>
        <h4 class="comment-group-title">评论({{ question.answers | length}})</h4>
        <form action="{{url_for('qa.public_answer')}}" method="post">
            <div class="form-group">
                <input type="text" placeholder="请填写评论" name="content" class="form-control">
                <input type="hidden" name="question_id" value="{{question.id}}">
            </div>
            <div class="form-group" style="text-align: right;">
                <button class="btn btn-primary">评论</button>
            </div>
        </form>
        <ul class="comment-group">
            {% for answer in question.answers %}
            <li>
                <div class="user-info">
                    <img class="avatar" src="{{url_for('static',filename='images/rkwork.jpg')}}" alt="">
                    <span class="username">{{answer.author.username}}</span>
                    <span class="create-time">{{answer.create_time}}</span>
                </div>
                <p class="comment-content">{{answer.content}}</p>
            </li>
            {% endfor  %}
        </ul>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title%}众承问答-首页{%endblock%}

{% block head%}

    <!-- <link rel="stylesheet" href="../static/css/index.css"> -->
    <link rel="stylesheet" href="{{url_for('static', filename ='css/index.css')}}">

{% endblock%}

{%block body%}
     <div class="row" style="margin-top: 20px;">
            <div class="col"></div>
            <div class="col-10">
                <ul class="question-ul">
                    {% for question in questions%}
                        <li>
                        <div class="side-question">
                            <img class="side-question-avatar" src="{{url_for('static', filename = 'images/muzi.png')}}" alt="" >
                        </div>
                        <div class="question-main">
                            <div class="question-title"><a href="{{url_for('qa.detail',qa_id = question.id)}}">{{question.title}}</a></div>                <!--问题详情，精妙！设置跳转连接-->
                            <div class="question-content">{{question.content}}</div>
                            <div class="question-detail">
                                <span class="question-author">{{question.author.username}}</span>
                                <span class="question-time">{{question.create_time}}</span>
                            </div>
                        </div>
                    </li>
                {% endfor %}
                </ul>
            </div>
            <div class="col"></div>
        </div>
{% endblock %}

<!--
    注释会影响html代码在flask中加载运行，所以就删掉吧
-->

templates/login.html
{% extends "base.html" %}

{% block title%}众承问答-登录{%endblock%}

{% block head%}{% endblock%}

{%block body%}
 <div class="row mt-4">
            <div class="col"></div>
            <div class="col">
                <form  method="POST">
                    <div class="form-group">
                        <label for="exampleInputEmail1">邮箱</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">密码</label>
                        <input type="password" name="password" class="form-control" id="exampleInputPassword1">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block">立即登录</button>
                    </div>
                </form>
            </div>
            <div class="col"></div>
        </div>
{%endblock%}

templates/public_question.html
{% extends "base.html" %}

{% block title%}众承-发布问答{%endblock%}

{% block head%}{% endblock%}

{%block body%}
<div class="row" style="margin-top: 20px;">
            <div class="col"></div>
            <div class="col-10">
                <h1 style="text-align: center;">发布问答</h1>
                <form action="#" method="post">
                    <div class="form-group">
                        <input type="text" name="title" class="form-control" placeholder="请输入标题">
                    </div>
                    <div class="form-group">
                        <textarea name="content" class="form-control" rows="10" placeholder="请输入内容"></textarea>
                    </div>
                    <div class="form-group" style="text-align: right;">
                        <button class="btn btn-primary">发布</button>
                    </div>
                </form>
            </div>
            <div class="col"></div>
        </div>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title %}众承问答-注册{% endblock %}


{% block head %}
    <script src="{{ url_for('static', filename='jquery/jquery.3.6.min.js') }}"></script>
    <script src="{{url_for('static', filename='js/register.js')}}"></script>
     <style>
        /* 样式优化 */
        #success-message {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 50px;
            background-color: #dff0d8;
            border: 1px solid #ccc;
            border-radius: 5px;
            margin-bottom: 20px;
            padding: 10px;
            font-weight: bold;
            color: #3c763d;
            display: none; /* 默认隐藏 */
        }
    </style>
{% endblock %}

{% block body %}
<!-- 在页面中添加一个用于显示成功消息的元素 -->
<div id="success-message" style="display: center;"></div>

 <div class="row mt-4">
            <div class="col"></div>
            <div class="col">
                <!-- <form method="POST" action="#"> -->      
                    <!--提交登录-->
                <form method="POST" >

                    <div class="form-group">
                        <label for="exampleInputEmail1">邮箱</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
                        <small id="emailHelp" class="form-text text-muted">我们不会把邮箱用于其他用户</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">验证码</label>
                        <div class="input-group">
                            <input type="text" class="form-control" name="captcha">
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">用户名</label>
                        <input type="text" class="form-control" name="username">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">密码</label>
                        <input type="password" class="form-control" id="exampleInputPassword1" name="password">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">确认密码</label>
                        <input type="password" class="form-control" name="password_confirm">
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">立即注册</button>
                </form>
            </div>
            <div class="col"></div>
        </div>
{% endblock %}

templates/rkwork.html
{% extends "base.html" %}
{% block title%}rk-问答平台导航页{%endblock%}

{%block body%}
<div class="row" style="display: flex; align-items: center; justify-content: center;">       
<div class="row">
  <div class="col-4">
    <div class="list-group" id="list-tab" role="tablist">
      <a class="list-group-item list-group-item-action active" id="list-home-list" data-toggle="list" href="{{url_for('auth.login')}}"> 登录首页</a>
      <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="{{url_for('auth.register')}}">注册首页</a>
      <a class="list-group-item list-group-item-action" id="list-messages-list" data-toggle="list" href="{{url_for('qa.index')}}">首页</a>
      <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="{{url_for('qa.public_answer')}}">问答页面</a>
    </div>
  </div>
  <div class="col-8">
    <div class="tab-content" id="nav-tabContent">
      <div class="tab-pane fade show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list">欢迎来到问答平台！
        你有问题需要解答吗？你想分享你的知识和经验吗？无论你是寻求答案还是愿意帮助他人，这里是一个互动交流的社区。</div>
      <div class="tab-pane fade" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list">...</div>
      <div class="tab-pane fade" id="list-messages" role="tabpanel" aria-labelledby="list-messages-list">...</div>
      <div class="tab-pane fade" id="list-settings" role="tabpanel" aria-labelledby="list-settings-list">...</div>
    </div>
  </div>
</div>
</div>

</body>
</html>

{% endblock %}